
services:

  db:
    image: mysql:8.0
    # Environment variables to setup postgres. Note that this is not secure, and
    # in production (or your project), you should store these in a different
    # file [5] or use secrets [6]. In no case should such files be uploaded to GitHub.
    environment:
      MYSQL_DATABASE: projectdatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    expose:
      - "3306"                                  
    volumes:
      - volumedb:/var/lib/mysql                 # Creates a docker managed volume to persist your data.
      - ./Database:/docker-entrypoint-initdb.d  # Binds ./database to docker-entrypoint-initdb.d.
                                                #   The postgres image will run any files in this directory on startup,
                                                #   in our case the file `init_data/create.sql`
    
  web:
    image: php:7.2.2-apache
    container_name: php_web                           

    depends_on:
      - db                                      # This indicates that docker should start the database first,
                                                # otherwise our website would have no data.
    ports:
        - "3000:3000"                           # Here we do need to publish the port for viewing on the host.
    volumes:
      - ./Project                               # Binds the current directory (containing our source code) into the image,
                                                #  so that changes made to the source code on the host
                                                #  are reflected witin the container.
    stdin_open: true
    tty: true

# This defines our volume(s), which will perist throughout startups.
# If you want to get rid of a hanging volume, e.g. to test your database init,
# run `docker-compose rm -v`. Note that this will remove ALL of your data, so
# be extra sure you've made a stable backup somewhere.
volumes:
  volumedb: {}
